# Application Settings

# LLM Configuration
llm_settings:
  provider: "openai"
  model: "gpt-3.5-turbo"
  temperature: 0.3
  max_tokens: 2000

# Web Scraping Settings
scraping:
  timeout: 30
  delay_between_requests: 2
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"

# Campaign Structure
campaign_structure:
  max_ad_groups: 15
  max_keywords_per_group: 20
  match_type_distribution:
    exact: 0.3
    phrase: 0.4
    broad: 0.3

# Keyword Research Settings
keyword_research:
  manual_expansion: false          # Disable deterministic expansion
  wordstream_scraping:
    enabled: true
    scrape_brand_website: true     # Scrape brand website once for base keywords
    scrape_competitors: true       # Scrape competitor websites 
    fallback_to_deterministic: false  # Don't fall back to estimates
    save_scraped_data: true
  data_priority:
    real_data_only: true           # Use ONLY real WordStream data  
    minimal_estimates: false       # No estimates - real data only
  
# WordStream Scraper Settings
wordstream_scraper:
  delays:
    page_load: 5
    form_fill: 5
    after_submit: 5
    after_modal: 5
    after_continue: 5
    results_load: 5
    after_extraction: 5
  extraction:
    page_limit: 1  # Only extract from first page
    use_default_location: true
